#!/usr/bin/env python3

import csv
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
TRAINING_CSV = DATA_DIR / "training_emails.csv"
EXPANDED_CSV = DATA_DIR / "training_emails_1000.csv"

EXPENSE_SAMPLES = [
    ["Invoice #7890", "Please find attached invoice for INR 8500 for web development services completed in March.", "billing@webdev.com", "EXPENSE"],
    ["Amazon order confirmed", "Your order #234-567 for ₹2899 has been shipped. Expected delivery: March 25.", "ship-confirm@amazon.in", "EXPENSE"],
    ["Spotify subscription renewed", "Your Spotify Premium subscription has been renewed. ₹119/month charged to your card.", "no-reply@spotify.com", "EXPENSE"],
    ["Bank debit alert", "INR 3500 debited from your account via UPI to Swiggy Foods. Ref: UPI123456789.", "alerts@hdfcbank.com", "EXPENSE"],
    ["Hotel booking confirmed", "Your booking at Taj Palace confirmed for 2 nights. Total: ₹18500. Check-in: March 30.", "bookings@tajhotels.com", "EXPENSE"],
    ["Zomato order receipt", "Order delivered! Total paid: ₹420 via Paytm. Restaurant: Pizza Hut.", "receipt@zomato.com", "EXPENSE"],
    ["Home loan EMI deducted", "Your home loan EMI of ₹32000 has been auto-debited. Account: HL-2024-789.", "emi@icicibank.com", "EXPENSE"],
    ["Jio recharge successful", "Your prepaid recharge of ₹299 for 9876543210 is successful. Validity: 28 days.", "recharge@jio.com", "EXPENSE"],
    ["UPI payment confirmed", "You paid ₹850 to Uber via UPI. Ride ID: UBER987654.", "payment@gpay.com", "EXPENSE"],
    ["Flipkart order shipped", "Your order #FL789 for ₹4500 has been shipped. Delivery by March 26.", "shipping@flipkart.com", "EXPENSE"],
    ["Electricity bill payment", "Your MSEDCL bill of ₹2100 for March is paid. Due date: March 25.", "payments@mahadiscom.in", "EXPENSE"],
    ["Car insurance premium", "Your car insurance premium of ₹14500 is due on April 5. Policy: CAR-2024-123.", "renewal@bhartiaxa.com", "EXPENSE"],
    ["Credit card payment", "Your HDFC credit card payment of ₹25000 is processed. Card ending 4567.", "cards@hdfcbank.com", "EXPENSE"],
    ["Uber ride receipt", "Uber ride complete. Fare: ₹180. Payment via Paytm. Ride ID: RIDE123456.", "receipts@uber.com", "EXPENSE"],
    ["Oyo room booking", "Oyo booking confirmed at Hotel Sunrise for 1 night. Total: ₹1200. Check-in: March 28.", "bookings@oyorooms.com", "EXPENSE"],
    ["Gym membership fee", "Your FitPath gym membership fee of ₹2400 is due for April. Renew to continue.", "billing@fitpath.com", "EXPENSE"],
    ["BigBasket order delivered", "Your grocery order worth ₹1800 has been delivered. Paid via credit card.", "orders@bigbasket.com", "EXPENSE"],
    ["Medical bill payment", "Apollo Pharmacy order #7890. Total: ₹560. Payment received via UPI.", "billing@apollo.com", "EXPENSE"],
    ["Airtel broadband bill", "Your Airtel broadband bill of ₹999 for March is paid. Due date: April 10.", "billing@airtel.in", "EXPENSE"],
    ["Mutual fund SIP", "Your SIP of ₹5000 in HDFC Equity Fund has been processed. NAV: ₹45.67.", "sip@hdfcfund.com", "EXPENSE"],
    ["BookMyShow tickets", "2 tickets for Avengers movie booked. Total: ₹900. Show: March 29, 7 PM.", "tickets@bookmyshow.com", "EXPENSE"],
    ["Amazon Pay balance", "You added ₹1000 to Amazon Pay balance from bank account.", "amazonpay@amazon.in", "EXPENSE"],
    ["Swiggy Instamart", "Your grocery order from Swiggy Instamart. Total: ₹380. Paid via GPay.", "orders@swiggy.com", "EXPENSE"],
    ["FASTag debit", "Your FASTag account debited ₹95 at Kherki Daula toll plaza. Balance: ₹450.", "fastag@icicibank.com", "EXPENSE"],
    ["Water bill paid", "Delhi Jal Board water bill of ₹320 paid for consumer 9876543.", "payments@djb.gov.in", "EXPENSE"],
    ["Netflix subscription", "Your Netflix Premium subscription renewed. ₹649/month charged to card.", "no-reply@netflix.com", "EXPENSE"],
    ["Income tax payment", "Advance tax payment of ₹35000 confirmed. Challan: 2345678.", "noreply@incometax.gov.in", "EXPENSE"],
    ["Fuel purchase", "HPCL fuel purchase: 12 litres. Total: ₹1350. Payment via debit card.", "receipt@hpcl.com", "EXPENSE"],
    ["School fee payment", "Tuition fee of ₹3500 for April received. Student: Amit Sharma.", "fees@davschool.edu", "EXPENSE"],
    ["Freelance payment", "Payment of USD 300 received for project #2024-04. Converted to ₹24750.", "payment@upwork.com", "EXPENSE"],
    ["GST invoice", "GST Invoice #INV-2024-089. Amount: ₹25000 + GST ₹4500.", "invoices@techvendor.co.in", "EXPENSE"],
    ["Office supplies", "Your order for office supplies from Amazon Business is confirmed. Total: ₹1800.", "business@amazon.in", "EXPENSE"],
    ["International transfer", "Wire transfer of USD 800 sent to account ending 6789. Ref: TXN20260324.", "wire@sbi.co.in", "EXPENSE"],
    ["Platform fee", "Marketplace platform fee of ₹290 charged to your seller account.", "fees@flipkart.com", "EXPENSE"],
    ["Cashback received", "₹120 PhonePe cashback credited for your recent Amazon purchase.", "rewards@phonepe.com", "EXPENSE"],
    ["Late fee charged", "Late payment fee of ₹75 added to your credit card bill.", "fees@icicibank.com", "EXPENSE"],
    ["Corporate card expense", "Corporate card transaction: ₹1800 at Petrol pump on March 24.", "corporate@hdfcbank.com", "EXPENSE"],
    ["AWS invoice", "Your AWS bill for March: $32.50. EC2 instances: 2. Due: April 15.", "billing@aws.amazon.com", "EXPENSE"],
    ["Domain renewal", "Your domain mywebsite.com renewed for 1 year. ₹599 charged.", "billing@godaddy.com", "EXPENSE"],
    ["Co-working invoice", "Invoice for WeWork desk booking. March: ₹7500. GST included.", "billing@wework.com", "EXPENSE"],
    ["Courier charges", "Delhivery courier charges of ₹180 for shipment #DEL123456.", "noreply@delhivery.com", "EXPENSE"],
    ["Dental bill", "Dental consultation fee: ₹1200. Dr. Mehta Dental Clinic.", "billing@mehtaclinic.com", "EXPENSE"],
    ["SaaS subscription", "Invoice for Slack Pro. Plan: Standard. ₹925/month per user.", "billing@slack.com", "EXPENSE"],
    ["Food delivery", "Your Dunzo order delivered. Total: ₹220 paid via UPI.", "orders@dunzo.com", "EXPENSE"],
    ["Online course", "You enrolled in 'Python for Data Science'. Amount: ₹1999.", "noreply@coursera.com", "EXPENSE"],
    ["Ola cab ride", "Ola ride fare: ₹150 paid via Ola Money. Ride ID: OLA987654.", "noreply@ola.com", "EXPENSE"],
    ["Conference fee", "Payment of ₹8000 for DevOps India Conference 2024 received.", "registration@devopsconf.com", "EXPENSE"],
    ["Printer supplies", "HP printer ink cartridge 2-pack ordered. ₹1200 charged to card.", "orders@hp.com", "EXPENSE"],
    ["News subscription", "The Hindu annual subscription of ₹999 activated.", "subscription@thehindu.com", "EXPENSE"],
    ["Personal loan EMI", "Your personal loan EMI of ₹8500 auto-debited on March 25.", "emi@axisbank.com", "EXPENSE"],
    ["Credit card bill", "Your ICICI credit card bill of ₹8750 is due on April 10.", "statement@icicibank.com", "EXPENSE"],
    ["Card transaction", "Your ICICI Bank Credit Card ending XX67 charged ₹320 at merchant.", "alerts@icicibank.com", "EXPENSE"],
    ["Transaction alert", "ICICI Bank Credit Card used for ₹1200 at online merchant.", "credit_cards@icicibank.com", "EXPENSE"],
    ["Debit alert", "Your HDFC savings account debited ₹25000 via NEFT. Balance: ₹45000.", "alerts@hdfcbank.com", "EXPENSE"],
    ["Kotak debit", "Kotak account debited ₹5000. Transaction ID: TXN2026032501.", "alerts@kotak.com", "EXPENSE"],
    ["UPI payment", "UPI payment of ₹450 to Zomato successful. Ref: UPI987654321.", "upi@paytm.com", "EXPENSE"],
    ["Card payment", "Credit card payment of ₹4339.85 received. Thank you.", "credit_cards@icicibank.com", "EXPENSE"],
    ["Auto debit", "Automatic payment of $8.99 processed for Netflix subscription.", "no-reply@netflix.com", "EXPENSE"],
    ["Online transaction", "INR 890 successful on Kotak debit card at online merchant.", "alerts@kotak.com", "EXPENSE"],
    ["MOTO payment", "INR 249 via MOTO/SI on Kotak card. Merchant: Flipkart.", "alerts@kotak.com", "EXPENSE"],
    ["Trading account", "Payment of ₹10000 received for Kotak trading account.", "noreply@kotaksecurities.com", "EXPENSE"],
    ["Dividend credited", "Dividend of ₹350 per share credited to your bank account.", "dividend@in.mpms.mufg.com", "EXPENSE"],
    ["Zerodha debit", "Zerodha trading account debited ₹5000 for equity purchase.", "noreply@zerodha.com", "EXPENSE"],
    ["SIP auto-debit", "SIP of ₹2500 for Axis Bluechip Fund debited.", "sip@axismf.com", "EXPENSE"],
    ["PhonePe payment", "Paid ₹280 to Swiggy via PhonePe UPI. Ref: UPI2026032501.", "noreply@phonepe.com", "EXPENSE"],
    ["Google Play", "Purchase of ₹89 on Google Play. Order: GPA.1234-5678.", "payments-noreply@google.com", "EXPENSE"],
    ["Apple subscription", "iCloud+ 50GB plan renewed. ₹75 charged to card.", "no-reply@email.apple.com", "EXPENSE"],
    ["Rapido ride", "Rapido bike ride complete. Fare: ₹35 paid via UPI.", "noreply@rapido.bike", "EXPENSE"],
    ["JioMart order", "JioMart grocery order delivered. Total: ₹650 via JioPay.", "orders@jiomart.com", "EXPENSE"],
    ["LPG booking", "Indane LPG cylinder booking confirmed. ₹903. Booking: HP987654.", "noreply@indianoil.in", "EXPENSE"],
    ["Razorpay payment", "Payment of ₹2500 to VendorX via Razorpay successful.", "noreply@razorpay.com", "EXPENSE"],
    ["ACT Fibernet", "ACT Fibernet bill of ₹1199 for March paid. Due: April 15.", "billing@actcorp.in", "EXPENSE"],
    ["Tata Play", "Tata Play DTH recharge ₹400 successful. Pack: Hindi Smart HD.", "recharge@tataplay.com", "EXPENSE"],
    ["Insurance premium", "Term life insurance premium ₹9500 auto-debited. Policy: LI-2024-890.", "premium@licindia.in", "EXPENSE"],
    ["Myntra order", "Myntra order confirmed. 3 items, total ₹2400 via credit card.", "orders@myntra.com", "EXPENSE"],
    ["IRCTC ticket", "Train ticket booked. PNR: 3456789012. Fare: ₹890. Class: 2A.", "irctc@irctc.co.in", "EXPENSE"],
    ["Paytm Postpaid", "Paytm Postpaid bill ₹1800 due April 5. Pay now.", "billing@paytm.com", "EXPENSE"],
    ["Urban Company", "Payment of ₹450 for AC service booking confirmed.", "noreply@urbancompany.com", "EXPENSE"],
    ["Nykaa shipped", "Nykaa order #NK890 worth ₹980 shipped. COD: ₹980.", "orders@nykaa.com", "EXPENSE"],
    ["Cult.fit", "Cult.fit membership renewed. ₹1499/month charged.", "billing@curefit.com", "EXPENSE"],
    ["SBI card", "INR 2800 spent on SBI credit card at Croma. Limit: ₹47000.", "alerts@sbi.co.in", "EXPENSE"],
    ["Airtel bill", "Airtel postpaid bill ₹699 paid via autopay.", "billing@airtel.in", "EXPENSE"],
    ["Meesho order", "Meesho order confirmed. 2 items, total ₹450 via UPI.", "orders@meesho.com", "EXPENSE"],
    ["Dunzo Daily", "Dunzo Daily order delivered. Total: ₹150 charged to wallet.", "noreply@dunzo.com", "EXPENSE"],
    ["YES Bank", "INR 650 debited from YES Bank for DMart purchase.", "alerts@yesbank.in", "EXPENSE"],
    ["Groww SIP", "Groww SIP of ₹3000 in Parag Parikh Flexi Cap processed.", "noreply@groww.in", "EXPENSE"],
    ["Licious order", "Licious order delivered. Total: ₹420 via PhonePe.", "orders@licious.in", "EXPENSE"],
    ["CRED cashback", "₹75 CRED cashback on credit card payment of ₹4500.", "rewards@cred.club", "EXPENSE"],
    ["FirstCry order", "FirstCry order #FC567 for baby products confirmed. ₹899.", "orders@firstcry.com", "EXPENSE"],
    ["Practo payment", "Payment of ₹350 for online consultation with Dr. Sharma.", "noreply@practo.com", "EXPENSE"],
    ["1mg order", "1mg medicine order placed. Total: ₹380. COD selected.", "orders@1mg.com", "EXPENSE"],
    ["BSNL landline", "BSNL landline bill ₹550 for March ready. Due: April 10.", "billing@bsnl.co.in", "EXPENSE"],
    ["Axis auto-debit", "Auto-debit of ₹4500 processed for loan EMI.", "alerts@axisbank.com", "EXPENSE"],
    ["FreshToHome", "FreshToHome order worth ₹590 shipped. Delivery tomorrow.", "orders@freshtohome.com", "EXPENSE"],
    ["Google One", "Google One 100GB plan renewed. ₹130/month to GPay.", "payments-noreply@google.com", "EXPENSE"],
    ["PVR tickets", "PVR ticket confirmed. 2 tickets: ₹600. Show: 6 PM.", "tickets@pvrcinemas.com", "EXPENSE"],
    ["Chai Point", "Chai Point order delivered. Total: ₹150 via Paytm.", "orders@chaipoint.com", "EXPENSE"],
    ["SBI Life", "SBI Life insurance premium ₹10500 for policy SL-890 deducted.", "premium@sbilife.co.in", "EXPENSE"],
    ["Kotak brokerage", "Brokerage charge ₹25 for equity trade. Contract: CN-2026-890.", "noreply@kotaksecurities.com", "EXPENSE"],
    ["Flipkart Pay Later", "Flipkart Pay Later bill ₹1800 due March 20.", "billing@flipkart.com", "EXPENSE"],
    ["Vi bill", "Vi postpaid bill ₹499 generated. Pay before March 28.", "billing@myvi.in", "EXPENSE"],
    ["Spencer's", "Spencer's grocery order ₹1280 delivered via credit card.", "orders@spencers.in", "EXPENSE"],
    ["Cleartrip", "Cleartrip booking confirmed. Hotel Park View 2 nights. ₹5800.", "bookings@cleartrip.com", "EXPENSE"],
    ["ICICI SIP", "ICICI Prudential SIP of ₹4000 processed successfully.", "sip@icicipru.com", "EXPENSE"],
    ["Bajaj EMI", "Bajaj Finserv EMI of ₹1800 auto-debited from account.", "emi@bajajfinserv.in", "EXPENSE"],
    ["Amazon Prime", "Amazon Prime renewed. ₹1499 charged to card.", "prime@amazon.in", "EXPENSE"],
    ["Kotak trade", "Trade executed: 15 shares Reliance at ₹2480. Total ₹37200.", "trades@kotaksecurities.com", "EXPENSE"],
    ["Upstox", "Brokerage ₹35 deducted for intraday trades on March 25.", "noreply@upstox.com", "EXPENSE"],
    ["Amazon Fresh", "Amazon Fresh grocery delivered. Total: ₹890 via Amazon Pay.", "fresh@amazon.in", "EXPENSE"],
    ["Paytm Mall", "Paytm Mall order for earbuds confirmed. ₹1299 via wallet.", "orders@paytmmall.com", "EXPENSE"],
    ["HDFC annual fee", "HDFC credit card annual fee ₹500 applied to Regalia card.", "cards@hdfcbank.com", "EXPENSE"],
    ["Gas bill", "Mahanagar Gas bill ₹780 for March generated. Due: April 10.", "billing@mahanagargas.com", "EXPENSE"],
    ["Society maintenance", "Monthly society maintenance ₹6500 debited.", "accounts@society.com", "EXPENSE"],
    ["India Post", "Speed post charges ₹95 for consignment EE987654321IN.", "noreply@indiapost.gov.in", "EXPENSE"],
    ["DigitalOcean", "DigitalOcean bill March: $18.00. Droplet 720 hours.", "billing@digitalocean.com", "EXPENSE"],
    ["Magazine", "India Today digital subscription ₹899 renewed.", "subscriptions@indiatoday.in", "EXPENSE"],
    ["NoBroker rent", "Monthly rent ₹20000 transferred via NoBroker Pay.", "payments@nobroker.in", "EXPENSE"],
    ["Lenskart", "Eye exam payment ₹650 at Lenskart Vision Care.", "billing@lenskart.com", "EXPENSE"],
    ["Pet vaccination", "Pet vaccination ₹1200 at Cessna Vet Clinic.", "billing@vetclinic.com", "EXPENSE"],
    ["UClean", "Laundry order ₹280 picked up. Payment via UPI.", "noreply@uclean.in", "EXPENSE"],
    ["Paytm FASTag", "Paytm FASTag charged ₹120 at toll plaza on NH-48.", "fastag@paytm.com", "EXPENSE"],
    ["JioSaavn", "JioSaavn Pro subscription ₹399/year renewed.", "billing@jiosaavn.com", "EXPENSE"],
    ["Decathlon", "Decathlon sports shoes confirmed. ₹2499 via UPI.", "orders@decathlon.in", "EXPENSE"],
    ["Pepperfry", "Pepperfry bookshelf delivered. ₹3500 via credit card.", "orders@pepperfry.com", "EXPENSE"],
    ["PharmEasy", "PharmEasy medicine order placed. ₹550 via wallet.", "orders@pharmeasy.in", "EXPENSE"],
    ["Ather", "Ather Grid charging complete. ₹35 charged to account.", "charging@ather.com", "EXPENSE"],
    ["Tata Power", "Tata Power EZ Charge bill: ₹95 for 7kWh via Paytm.", "billing@tatapowerez.com", "EXPENSE"],
    ["Home loan EMI", "HDFC home loan EMI ₹30000 deducted for March.", "homeloan@hdfc.com", "EXPENSE"],
    ["NoBroker stamp duty", "Stamp duty ₹450 for rental agreement via NoBroker.", "charges@nobroker.in", "EXPENSE"],
    ["Delhivery insurance", "Shipping insurance ₹65 charged for Meesho order.", "charges@delhivery.com", "EXPENSE"],
    ["Amazon Subscribe", "Subscribe & Save order placed. 4 items ₹1650.", "subscribe@amazon.in", "EXPENSE"],
    ["Swiggy Genie", "Swiggy Genie delivery completed. Charges: ₹59 via wallet.", "noreply@swiggy.com", "EXPENSE"],
    ["Boat warranty", "Extended warranty for Boat Airdopes. ₹249 via card.", "orders@boat-lifestyle.com", "EXPENSE"],
    ["Samsung repair", "Samsung service center charge ₹3200 for screen repair.", "service@samsung.com", "EXPENSE"],
    ["LensDen", "LensDen contact lens order confirmed. ₹980 shipped in 2 days.", "orders@lensden.com", "EXPENSE"],
    ["DTDC", "DTDC courier charges ₹150 for domestic parcel shipment.", "noreply@dtdc.com", "EXPENSE"],
    ["BigBasket membership", "BigBasket BB Star annual membership activated. ₹299.", "membership@bigbasket.com", "EXPENSE"],
    ["Park+", "Parking fee ₹75 via Park+ at Select Citywalk mall.", "payments@parkplus.io", "EXPENSE"],
    ["EaseMyTrip", "EaseMyTrip bus ticket booked. Delhi to Jaipur. ₹680.", "bookings@easemytrip.in", "EXPENSE"],
    ["Noise watch", "Noise ColorFit Pro 5 order confirmed. ₹2999 via PhonePe.", "orders@gonoise.com", "EXPENSE"],
    ["Byju's", "Byju's subscription renewed. Monthly charge: ₹1599.", "billing@byjus.com", "EXPENSE"],
    ["IndiaMART", "IndiaMART lead purchase ₹4000 processed.", "billing@indiamart.com", "EXPENSE"],
    ["WazirX", "Bought 0.003 BTC for ₹15000 on WazirX. Fee: ₹45.", "noreply@wazirx.com", "EXPENSE"],
    ["Angel One", "Brokerage ₹25 charged for F&O trade. Contract note attached.", "trades@angelone.in", "EXPENSE"],
    ["ICICI locker", "Annual locker rental ₹4000 debited from ICICI account.", "charges@icicibank.com", "EXPENSE"],
    ["Passport fee", "Passport application fee ₹1500 paid online. ID: PA-2026-890.", "receipts@passportindia.gov.in", "EXPENSE"],
    ["MakeMyTrip cab", "MakeMyTrip outstation cab booked. Delhi to Agra. ₹4200.", "cabs@makemytrip.com", "EXPENSE"],
    ["Apollo 247", "Teleconsultation payment ₹350 for Dr. Patel on Apollo 247.", "billing@apollo247.com", "EXPENSE"],
    ["Udaan", "Udaan wholesale order for supplies shipped. Total ₹7500.", "orders@udaan.com", "EXPENSE"],
    ["Country Delight", "Country Delight monthly milk bill: ₹980 auto-deducted.", "billing@countrydelight.in", "EXPENSE"],
    ["IRCTC food", "IRCTC e-catering order confirmed. Delivery at Kanpur station. ₹290.", "ecatering@irctc.co.in", "EXPENSE"],
    ["Zomato Gold", "Zomato Gold membership renewed 3 months. ₹250 to card.", "membership@zomato.com", "EXPENSE"],
    ["Oyo booking", "Oyo booking at Hotel Lake View 1 night confirmed. ₹1500.", "bookings@oyorooms.com", "EXPENSE"],
    ["HealthifyMe", "HealthifyMe Pro subscription renewed. ₹349/month.", "billing@healthifyme.com", "EXPENSE"],
    ["Zerodha AMC", "Zerodha demat AMC ₹250 for annual maintenance charged.", "charges@zerodha.com", "EXPENSE"],
    ["Aquaguard", "Aquaguard annual maintenance ₹2200 debited from account.", "service@eureka-forbes.com", "EXPENSE"],
    ["TDS", "TDS of ₹1200 deducted on FD interest for Q4 FY26.", "tds@sbi.co.in", "EXPENSE"],
    ["Driving license", "Driving license renewal fee ₹500 paid online. ID: DL-2026-890.", "receipts@parivahan.gov.in", "EXPENSE"],
    ["BookMyShow event", "BookMyShow booking for concert. 2 tickets ₹2200 each. Total: ₹4400.", "events@bookmyshow.com", "EXPENSE"],
    ["Urban Company", "Salon at home service payment ₹950 via Urban Company.", "noreply@urbancompany.com", "EXPENSE"],
    ["Property tax", "Municipal corporation property tax ₹7200 for FY 2026-27 confirmed.", "receipts@mcgm.gov.in", "EXPENSE"],
    ["Bike service", "Royal Enfield service center bill: ₹2800 for 10000km service.", "service@royalenfield.com", "EXPENSE"],
    ["Unacademy", "Unacademy Plus subscription renewed. ₹999/month.", "billing@unacademy.com", "EXPENSE"],
    ["Restaurant bill", "Payment of ₹1200 made at Barbeque Nation via UPI.", "payment@upi.com", "EXPENSE"],
    ["Grocery store", "DMart purchase of ₹850 paid via debit card.", "store@dmart.in", "EXPENSE"],
    ["Petrol pump", "Fuel purchase at IOCL pump: 10 litres ₹1100 via card.", "receipt@iocl.com", "EXPENSE"],
    ["Medical store", "Pharmacy bill ₹420 paid at local chemist.", "billing@chemist.com", "EXPENSE"],
    ["Clothing store", "H&M purchase ₹1899 paid via credit card.", "orders@hm.com", "EXPENSE"],
    ["Electronics store", "Croma purchase ₹6500 for headphones via EMI.", "orders@croma.com", "EXPENSE"],
    ["Online course", "Udemy course 'Advanced Python' purchased for ₹1299.", "noreply@udemy.com", "EXPENSE"],
    ["Software license", "Microsoft Office 365 annual subscription ₹5299 renewed.", "billing@microsoft.com", "EXPENSE"],
    ["Cloud storage", "Google Cloud storage bill $15.50 for March.", "billing@google.com", "EXPENSE"],
    ["Web hosting", "Bluehost hosting bill ₹450 for March due April 15.", "billing@bluehost.com", "EXPENSE"],
    ["Domain name", "Domain newdomain.com registered for ₹799 for 1 year.", "billing@namecheap.com", "EXPENSE"],
    ["SSL certificate", "SSL certificate renewed for ₹1299/year.", "billing@godaddy.com", "EXPENSE"],
    ["Email marketing", "Mailchimp monthly plan ₹950 charged to card.", "billing@mailchimp.com", "EXPENSE"],
    ["Project management", "Asana Premium subscription ₹450/month charged.", "billing@asana.com", "EXPENSE"],
    ["Video conferencing", "Zoom Pro subscription ₹1200/month charged.", "billing@zoom.us", "EXPENSE"],
    ["Design tool", "Canva Pro subscription ₹499/month charged.", "billing@canva.com", "EXPENSE"],
    ["Stock photos", "Shutterstock subscription ₹899/month charged.", "billing@shutterstock.com", "EXPENSE"],
    ["Music streaming", "YouTube Music Premium ₹129/month charged.", "billing@youtube.com", "EXPENSE"],
    ["Cloud backup", "Backblaze backup subscription ₹550/month charged.", "billing@backblaze.com", "EXPENSE"],
    ["VPN service", "NordVPN subscription ₹850/year charged.", "billing@nordvpn.com", "EXPENSE"],
    ["Password manager", "1Password subscription ₹280/month charged.", "billing@1password.com", "EXPENSE"],
    ["Development tool", "GitHub Copilot subscription ₹750/month charged.", "billing@github.com", "EXPENSE"],
    ["API service", "OpenAI API usage $42.00 for March.", "billing@openai.com", "EXPENSE"],
    ["Database service", "MongoDB Atlas bill $28.50 for March.", "billing@mongodb.com", "EXPENSE"],
    ["CDN service", "Cloudflare bill $12.00 for March usage.", "billing@cloudflare.com", "EXPENSE"],
    ["Analytics tool", "Google Analytics 360 subscription ₹15000/month.", "billing@analytics.com", "EXPENSE"],
    ["Marketing automation", "HubSpot subscription ₹12000/month charged.", "billing@hubspot.com", "EXPENSE"],
    ["CRM software", "Salesforce subscription ₹8500/month charged.", "billing@salesforce.com", "EXPENSE"],
    ["HR software", "Zoho People subscription ₹3500/month charged.", "billing@zoho.com", "EXPENSE"],
    ["Accounting", "QuickBooks subscription ₹1800/month charged.", "billing@quickbooks.com", "EXPENSE"],
    ["Legal software", "DocuSign subscription ₹2500/month charged.", "billing@docusign.com", "EXPENSE"],
    ["Team communication", "Slack subscription ₹780/month per user charged.", "billing@slack.com", "EXPENSE"],
    ["File storage", "Dropbox Business subscription ₹1200/month charged.", "billing@dropbox.com", "EXPENSE"],
    ["Video editing", "Adobe Premiere Pro subscription ₹2200/month charged.", "billing@adobe.com", "EXPENSE"],
    ["Photo editing", "Adobe Lightroom subscription ₹950/month charged.", "billing@adobe.com", "EXPENSE"],
    ["Graphic design", "Adobe Illustrator subscription ₹1800/month charged.", "billing@adobe.com", "EXPENSE"],
    ["Prototyping tool", "Figma Professional subscription ₹1200/month charged.", "billing@figma.com", "EXPENSE"],
    ["Code editor", "JetBrains PhpStorm subscription ₹1500/month charged.", "billing@jetbrains.com", "EXPENSE"],
    ["Database tool", "DataGrip subscription ₹950/month charged.", "billing@jetbrains.com", "EXPENSE"],
    ["Version control", "GitHub Enterprise subscription $25/user/month.", "billing@github.com", "EXPENSE"],
    ["CI/CD", "GitLab Premium subscription $19/user/month.", "billing@gitlab.com", "EXPENSE"],
    ["Container registry", "Docker Hub Pro subscription $5/month charged.", "billing@docker.com", "EXPENSE"],
    ["Kubernetes", "AWS EKS bill $45.00 for March cluster usage.", "billing@aws.amazon.com", "EXPENSE"],
    ["Serverless", "AWS Lambda bill $22.50 for March usage.", "billing@aws.amazon.com", "EXPENSE"],
    ["Database AWS", "AWS RDS bill $35.00 for March.", "billing@aws.amazon.com", "EXPENSE"],
    ["Storage AWS", "AWS S3 bill $18.00 for March storage.", "billing@aws.amazon.com", "EXPENSE"],
    ["CDN AWS", "AWS CloudFront bill $8.50 for March bandwidth.", "billing@aws.amazon.com", "EXPENSE"],
    ["Monitoring", "Datadog subscription ₹4500/month charged.", "billing@datadoghq.com", "EXPENSE"],
    ["Logging", "Loggly subscription ₹2800/month charged.", "billing@loggly.com", "EXPENSE"],
    ["APM", "New Relic subscription ₹6500/month charged.", "billing@newrelic.com", "EXPENSE"],
    ["Error tracking", "Sentry subscription ₹1800/month charged.", "billing@sentry.io", "EXPENSE"],
    ["Security scan", "Snyk subscription ₹3500/month charged.", "billing@snyk.io", "EXPENSE"],
    ["Code review", "SonarCloud subscription ₹2200/month charged.", "billing@sonarsource.com", "EXPENSE"],
    ["Testing", "BrowserStack subscription ₹4200/month charged.", "billing@browserstack.com", "EXPENSE"],
    ["Mobile testing", "TestFairy subscription ₹1800/month charged.", "billing@testfairy.com", "EXPENSE"],
    ["Performance", "WebPageTest subscription ₹950/month charged.", "billing@webpagetest.org", "EXPENSE"],
    ["SEO tools", "SEMrush subscription ₹8500/month charged.", "billing@semrush.com", "EXPENSE"],
    ["Email tools", "Mailgun subscription ₹1200/month charged.", "billing@mailgun.com", "EXPENSE"],
    ["SMS", "Twilio subscription ₹2500/month charged.", "billing@twilio.com", "EXPENSE"],
    ["Push notifications", "OneSignal subscription ₹950/month charged.", "billing@onesignal.com", "EXPENSE"],
    ["Chat widget", "Intercom subscription ₹4500/month charged.", "billing@intercom.com", "EXPENSE"],
    ["Help desk", "Zendesk subscription ₹3800/month charged.", "billing@zendesk.com", "EXPENSE"],
    ["Customer support", "Freshdesk subscription ₹3200/month charged.", "billing@freshdesk.com", "EXPENSE"],
    ["Survey tool", "Typeform subscription ₹950/month charged.", "billing@typeform.com", "EXPENSE"],
    ["Forms", "Google Forms workspace subscription ₹1200/month.", "billing@google.com", "EXPENSE"],
    ["Spreadsheets", "Google Sheets workspace subscription ₹1200/month.", "billing@google.com", "EXPENSE"],
    ["Documents", "Google Docs workspace subscription ₹1200/month.", "billing@google.com", "EXPENSE"],
    ["Presentations", "Google Slides workspace subscription ₹1200/month.", "billing@google.com", "EXPENSE"],
    ["Cloud office", "Microsoft 365 Business Premium ₹850/user/month.", "billing@microsoft.com", "EXPENSE"],
    ["Email provider", "Google Workspace Business ₹680/user/month.", "billing@google.com", "EXPENSE"],
    ["Cloud office", "Zoho Workplace ₹350/user/month.", "billing@zoho.com", "EXPENSE"],
    ["HR", "BambooHR subscription ₹4500/month charged.", "billing@bamboohr.com", "EXPENSE"],
    ["Recruitment", "Greenhouse subscription ₹8500/month charged.", "billing@greenhouse.io", "EXPENSE"],
    ["Performance", "Lattice subscription ₹3200/month charged.", "billing@lattice.com", "EXPENSE"],
    ["Training", "Udemy Business subscription ₹1800/user/month.", "billing@udemy.com", "EXPENSE"],
    ["Learning", "Coursera for Business ₹850/user/month.", "billing@coursera.com", "EXPENSE"],
    ["Development", "Pluralsight subscription ₹1200/user/month.", "billing@pluralsight.com", "EXPENSE"],
    ["Design", "Skillshare subscription ₹350/user/month.", "billing@skillshare.com", "EXPENSE"],
    ["Books", "Scribd subscription ₹350/month charged.", "billing@scribd.com", "EXPENSE"],
    ["Audiobooks", "Audible subscription ₹650/month charged.", "billing@audible.com", "EXPENSE"],
    ["Magazines", "Readly subscription ₹450/month charged.", "billing@readly.com", "EXPENSE"],
    ["News", "The New York Times subscription ₹650/month charged.", "billing@nytimes.com", "EXPENSE"],
    ["Finance app", "YNAB subscription ₹450/month charged.", "billing@ynab.com", "EXPENSE"],
    ["Investment", "Robinhood Gold subscription ₹350/month charged.", "billing@robinhood.com", "EXPENSE"],
    ["Trading", "StockTwits Premium subscription ₹250/month charged.", "billing@stocktwits.com", "EXPENSE"],
    ["Crypto", "Coinbase One subscription ₹950/month charged.", "billing@coinbase.com", "EXPENSE"],
    ["Tax", "TurboTax subscription ₹650/season charged.", "billing@turbotax.com", "EXPENSE"],
    ["Accounting", "Xero subscription ₹1200/month charged.", "billing@xero.com", "EXPENSE"],
    ["Invoice", "FreshBooks subscription ₹450/month charged.", "billing@freshbooks.com", "EXPENSE"],
    ["Payments", "Stripe account fees 2.9% + ₹30 per transaction.", "billing@stripe.com", "EXPENSE"],
    ["E-commerce", "Shopify subscription ₹1800/month charged.", "billing@shopify.com", "EXPENSE"],
    ["Marketing", "Klaviyo subscription ₹950/month charged.", "billing@klaviyo.com", "EXPENSE"],
    ["Social media", "Hootsuite subscription ₹3800/month charged.", "billing@hootsuite.com", "EXPENSE"],
    ["Social media", "Buffer subscription ₹950/month charged.", "billing@buffer.com", "EXPENSE"],
    ["Social media", "Sprout Social subscription ₹8500/month charged.", "billing@sproutsocial.com", "EXPENSE"],
    ["Analytics", "Mixpanel subscription ₹8500/month charged.", "billing@mixpanel.com", "EXPENSE"],
    ["Analytics", "Amplitude subscription ₹6500/month charged.", "billing@amplitude.com", "EXPENSE"],
    ["Analytics", "Heap subscription ₹4500/month charged.", "billing@heapanalytics.com", "EXPENSE"],
    ["A/B testing", "Optimizely subscription ₹12000/month charged.", "billing@optimizely.com", "EXPENSE"],
    ["Personalization", "Dynamic Yield subscription ₹18000/month.", "billing@dynamicyield.com", "EXPENSE"],
    ["Email deliverability", "SendGrid subscription ₹2500/month charged.", "billing@sendgrid.com", "EXPENSE"],
    ["Email marketing", "Campaign Monitor subscription ₹1200/month.", "billing@campaignmonitor.com", "EXPENSE"],
    ["Marketing automation", "ActiveCampaign subscription ₹2500/month.", "billing@activecampaign.com", "EXPENSE"],
    ["Landing pages", "Unbounce subscription ₹1200/month charged.", "billing@unbounce.com", "EXPENSE"],
    ["Forms", "Typeform subscription ₹950/month charged.", "billing@typeform.com", "EXPENSE"],
    ["Surveys", "SurveyMonkey subscription ₹850/month charged.", "billing@surveymonkey.com", "EXPENSE"],
    ["Feedback", "Hotjar subscription ₹1200/month charged.", "billing@hotjar.com", "EXPENSE"],
    ["User testing", "UserTesting subscription ₹9500/month charged.", "billing@usertesting.com", "EXPENSE"],
    ["Accessibility", "Axe DevTools subscription ₹950/month.", "billing@deque.com", "EXPENSE"],
    ["SEO", "Ahrefs subscription ₹9500/month charged.", "billing@ahrefs.com", "EXPENSE"],
    ["SEO", "Moz Pro subscription ₹6500/month charged.", "billing@moz.com", "EXPENSE"],
    ["Content", "BuzzStream subscription ₹2500/month charged.", "billing@buzzstream.com", "EXPENSE"],
    ["PR", "Cision subscription ₹18000/month charged.", "billing@cision.com", "EXPENSE"],
    ["Social listening", "Brandwatch subscription ₹35000/month.", "billing@brandwatch.com", "EXPENSE"],
    ["Influencer", "AspireIQ subscription ₹12000/month.", "billing@aspireiq.com", "EXPENSE"],
    ["Affiliate", "Impact subscription ₹8500/month charged.", "billing@impact.com", "EXPENSE"],
    ["Referral", "ReferralCandy subscription ₹950/month.", "billing@referralcandy.com", "EXPENSE"],
    ["Loyalty", "Smile.io subscription ₹850/month charged.", "billing@smile.io", "EXPENSE"],
    ["Reviews", "Yotpo subscription ₹3200/month charged.", "billing@yotpo.com", "EXPENSE"],
    ["UGC", "TINT subscription ₹2500/month charged.", "billing@tint.com", "EXPENSE"],
    ["Live chat", "LiveChat subscription ₹1200/month charged.", "billing@livechat.com", "EXPENSE"],
    ["Chatbot", "Intercom subscription ₹4500/month charged.", "billing@intercom.com", "EXPENSE"],
    ["Help center", "HelpScout subscription ₹2500/month.", "billing@helpscout.com", "EXPENSE"],
    ["Knowledge base", "Notion subscription ₹800/user/month.", "billing@notion.so", "EXPENSE"],
    ["Documentation", "GitBook subscription ₹1800/month.", "billing@gitbook.com", "EXPENSE"],
    ["Project mgmt", "Monday.com subscription ₹650/user/month.", "billing@monday.com", "EXPENSE"],
    ["Project mgmt", "ClickUp subscription ₹450/user/month.", "billing@clickup.com", "EXPENSE"],
    ["Project mgmt", "Smartsheet subscription ₹950/user/month.", "billing@smartsheet.com", "EXPENSE"],
    ["Project mgmt", "Wrike subscription ₹1200/user/month.", "billing@wrike.com", "EXPENSE"],
    ["Task mgmt", "Todoist Business subscription ₹450/user/month.", "billing@todoist.com", "EXPENSE"],
    ["Notes", "Evernote Business subscription ₹950/user/month.", "billing@evernote.com", "EXPENSE"],
    ["Whiteboard", "Miro subscription ₹1200/user/month.", "billing@miro.com", "EXPENSE"],
    ["Whiteboard", "Mural subscription ₹950/user/month.", "billing@mural.co", "EXPENSE"],
    ["Diagram", "Lucidchart subscription ₹950/user/month.", "billing@lucidchart.com", "EXPENSE"],
    ["Mind mapping", "MindMeister subscription ₹850/month.", "billing@mindmeister.com", "EXPENSE"],
    ["Wireframing", "Balsamiq subscription ₹650/month.", "billing@balsamiq.com", "EXPENSE"],
    ["Prototyping", "InVision subscription ₹850/month.", "billing@invisionapp.com", "EXPENSE"],
    ["Design handoff", "Zeplin subscription ₹650/month.", "billing@zeplin.com", "EXPENSE"],
    ["Design system", "Abstract subscription ₹650/user/month.", "billing@abstract.com", "EXPENSE"],
    ["Version control", "Figma subscription ₹1200/month charged.", "billing@figma.com", "EXPENSE"],
    ["Code review", "CodeSandbox subscription ₹850/month.", "billing@codesandbox.io", "EXPENSE"],
    ["IDE", "Replit subscription ₹850/month.", "billing@replit.com", "EXPENSE"],
    ["Cloud IDE", "Gitpod subscription ₹950/user/month.", "billing@gitpod.io", "EXPENSE"],
    ["Database", "Supabase subscription $25/month.", "billing@supabase.com", "EXPENSE"],
    ["Database", "PlanetScale subscription $29/month.", "billing@planetscale.com", "EXPENSE"],
    ["Database", "Neon database bill $15.00 for March.", "billing@neon.tech", "EXPENSE"],
    ["Backend", "Firebase Spark plan free tier usage exceeded.", "billing@firebase.com", "EXPENSE"],
    ["Backend", "AWS AppSync bill $18.50 for March.", "billing@aws.amazon.com", "EXPENSE"],
    ["API gateway", "Kong Enterprise subscription ₹45000/month.", "billing@konghq.com", "EXPENSE"],
    ["API mgmt", "Postman subscription ₹950/user/month.", "billing@postman.com", "EXPENSE"],
    ["Testing", "Postman API testing subscription ₹950/month.", "billing@postman.com", "EXPENSE"],
    ["Documentation", "SwaggerHub subscription ₹450/month.", "billing@swaggerhub.com", "EXPENSE"],
    ["Monitoring", "Grafana Cloud subscription ₹8500/month.", "billing@grafana.com", "EXPENSE"],
    ["Metrics", "InfluxDB Cloud subscription ₹5500/month.", "billing@influxdata.com", "EXPENSE"],
    ["Logging", "Logz.io subscription ₹12000/month.", "billing@logz.io", "EXPENSE"],
    ["Tracing", "Jaeger Cloud subscription ₹8500/month.", "billing@jaegertracing.io", "EXPENSE"],
    ["APM", "Dynatrace subscription ₹85000/month.", "billing@dynatrace.com", "EXPENSE"],
    ["Security", "Snyk Enterprise subscription ₹35000/month.", "billing@snyk.io", "EXPENSE"],
    ["Security", "SonarQube Enterprise subscription ₹45000/month.", "billing@sonarsource.com", "EXPENSE"],
    ["Security", "Veracode subscription ₹95000/month.", "billing@veracode.com", "EXPENSE"],
    ["Security", "WhiteSource subscription ₹25000/month.", "billing@whitesourcesoftware.com", "EXPENSE"],
    ["Container security", "Aqua Security subscription ₹18000/month.", "billing@aquasec.com", "EXPENSE"],
    ["Cloud security", "Orca Security subscription ₹25000/month.", "billing@orca.security", "EXPENSE"],
    ["Compliance", "Vanta subscription ₹35000/month.", "billing@vanta.com", "EXPENSE"],
    ["Compliance", "Drata subscription ₹28000/month.", "billing@drata.com", "EXPENSE"],
    ["Compliance", "Secureframe subscription ₹22000/month.", "billing@secureframe.com", "EXPENSE"],
    ["Compliance", "Tugboat Logic subscription ₹18000/month.", "billing@tugboatlogic.com", "EXPENSE"],
    ["Identity", "Okta subscription ₹2500/user/month.", "billing@okta.com", "EXPENSE"],
    ["Identity", "Auth0 subscription ₹4500/month.", "billing@auth0.com", "EXPENSE"],
    ["Identity", "OneLogin subscription ₹3200/month.", "billing@onelogin.com", "EXPENSE"],
    ["Identity", "JumpCloud subscription ₹2500/month.", "billing@jumpcloud.com", "EXPENSE"],
    ["SSO", "Ping Identity subscription ₹8500/month.", "billing@pingidentity.com", "EXPENSE"],
    ["MFA", "Duo Security subscription ₹8500/month.", "billing@duo.com", "EXPENSE"],
    ["Access mgmt", "BeyondTrust subscription ₹12000/month.", "billing@beyondtrust.com", "EXPENSE"],
    ["Privileged access", "CyberArk subscription ₹45000/month.", "billing@cyberark.com", "EXPENSE"],
    ["Secrets mgmt", "HashiCorp Vault subscription ₹15000/month.", "billing@hashicorp.com", "EXPENSE"],
    ["Container registry", "Harbor subscription ₹8500/month.", "billing@goharbor.io", "EXPENSE"],
    ["CI/CD", "Jenkins X subscription ₹12000/month.", "billing@jenkins.io", "EXPENSE"],
    ["CI/CD", "CircleCI subscription ₹8500/month.", "billing@circleci.com", "EXPENSE"],
    ["CI/CD", "Travis CI subscription ₹6500/month.", "billing@travis-ci.com", "EXPENSE"],
    ["CI/CD", "Codeship subscription ₹4500/month.", "billing@codeship.com", "EXPENSE"],
    ["CI/CD", "Buildkite subscription ₹6500/month.", "billing@buildkite.com", "EXPENSE"],
    ["CI/CD", "Semaphore subscription ₹4500/month.", "billing@semaphoreci.com", "EXPENSE"],
    ["CI/CD", "Heroku CI subscription ₹3500/month.", "billing@heroku.com", "EXPENSE"],
    ["PaaS", "Heroku subscription ₹4500/month for dyno usage.", "billing@heroku.com", "EXPENSE"],
    ["PaaS", "Render subscription ₹2500/month.", "billing@render.com", "EXPENSE"],
    ["PaaS", "Railway subscription ₹1800/month.", "billing@railway.app", "EXPENSE"],
    ["PaaS", "Fly.io subscription ₹950/month.", "billing@fly.io", "EXPENSE"],
    ["PaaS", "DigitalOcean App Platform ₹1800/month.", "billing@digitalocean.com", "EXPENSE"],
    ["PaaS", "Google Cloud Run bill $45.00 for March.", "billing@google.com", "EXPENSE"],
    ["PaaS", "AWS Elastic Beanstalk bill $35.00.", "billing@aws.amazon.com", "EXPENSE"],
    ["PaaS", "Azure App Service bill $42.00 for March.", "billing@microsoft.com", "EXPENSE"],
    ["Serverless", "Vercel Pro subscription ₹1200/month.", "billing@vercel.com", "EXPENSE"],
    ["Serverless", "Netlify Pro subscription ₹950/month.", "billing@netlify.com", "EXPENSE"],
    ["Serverless", "Cloudflare Workers subscription ₹850/month.", "billing@cloudflare.com", "EXPENSE"],
    ["Edge", "Fastly subscription ₹8500/month.", "billing@fastly.com", "EXPENSE"],
    ["CDN", "Akamai subscription ₹35000/month.", "billing@akamai.com", "EXPENSE"],
    ["CDN", "CloudFront subscription AWS bill included.", "billing@aws.amazon.com", "EXPENSE"],
    ["DNS", "Cloudflare DNS subscription ₹850/month.", "billing@cloudflare.com", "EXPENSE"],
    ["DNS", "AWS Route 53 bill $8.50 for March.", "billing@aws.amazon.com", "EXPENSE"],
    ["Load balancer", "AWS ALB bill $15.00 for March.", "billing@aws.amazon.com", "EXPENSE"],
    ["Load balancer", "NGINX Ingress Controller subscription ₹2500/month.", "billing@nginx.com", "EXPENSE"],
    ["API gateway", "Kong Cloud subscription ₹8500/month.", "billing@konghq.com", "EXPENSE"],
    ["Service mesh", "Istio subscription ₹12000/month.", "billing@istio.io", "EXPENSE"],
    ["Observability", "Grafana subscription ₹4500/month.", "billing@grafana.com", "EXPENSE"],
    ["Observability", "Prometheus subscription ₹2500/month.", "billing@prometheus.io", "EXPENSE"],
    ["Observability", "Thanos subscription ₹4500/month.", "billing@thanos.io", "EXPENSE"],
    ["Observability", "VictoriaMetrics subscription ₹2500/month.", "billing@victoriametrics.com", "EXPENSE"],
    ["Logging", "ELK Stack subscription ₹8500/month.", "billing@elastic.co", "EXPENSE"],
    ["Logging", "Splunk subscription ₹45000/month.", "billing@splunk.com", "EXPENSE"],
    ["Logging", "Logstash subscription ₹2500/month.", "billing@elastic.co", "EXPENSE"],
    ["SIEM", "CrowdStrike subscription ₹45000/month.", "billing@crowdstrike.com", "EXPENSE"],
    ["SIEM", "Splunk SIEM subscription ₹65000/month.", "billing@splunk.com", "EXPENSE"],
    ["SIEM", "LogRhythm subscription ₹35000/month.", "billing@logrhythm.com", "EXPENSE"],
    ["EDR", "Carbon Black subscription ₹25000/month.", "billing@carbonblack.com", "EXPENSE"],
    ["EDR", "SentinelOne subscription ₹35000/month.", "billing@sentinelone.com", "EXPENSE"],
    ["EDR", "Cylance subscription ₹28000/month.", "billing@cylance.com", "EXPENSE"],
    ["Antivirus", "Symantec Endpoint subscription ₹25000/month.", "billing@symantec.com", "EXPENSE"],
    ["Antivirus", "McAfee Enterprise subscription ₹22000/month.", "billing@mcafee.com", "EXPENSE"],
    ["Antivirus", "Kaspersky Enterprise subscription ₹18000/month.", "billing@kaspersky.com", "EXPENSE"],
    ["Firewall", "Palo Alto Networks subscription ₹65000/month.", "billing@paloaltonetworks.com", "EXPENSE"],
    ["Firewall", "Fortinet subscription ₹45000/month.", "billing@fortinet.com", "EXPENSE"],
    ["Firewall", "Check Point subscription ₹55000/month.", "billing@checkpoint.com", "EXPENSE"],
    ["VPN", "NordVPN Business subscription ₹1200/user/month.", "billing@nordvpn.com", "EXPENSE"],
    ["VPN", "ExpressVPN Business subscription ₹1500/user/month.", "billing@expressvpn.com", "EXPENSE"],
    ["VPN", "Surfshark Business subscription ₹950/user/month.", "billing@surfshark.com", "EXPENSE"],
    ["ZTNA", "Cloudflare Access subscription ₹2500/month.", "billing@cloudflare.com", "EXPENSE"],
    ["ZTNA", "Twingate subscription ₹3500/month.", "billing@twingate.com", "EXPENSE"],
    ["ZTNA", "Tailscale Business subscription ₹8500/month.", "billing@tailscale.com", "EXPENSE"],
    ["SASE", "Cato Networks subscription ₹18000/month.", "billing@catonetworks.com", "EXPENSE"],
    ["SASE", "Versa Networks subscription ₹22000/month.", "billing@versanetworks.com", "EXPENSE"],
    ["SASE", "Cisco SASE subscription ₹45000/month.", "billing@cisco.com", "EXPENSE"],
    ["DLP", "Forcepoint DLP subscription ₹35000/month.", "billing@forcepoint.com", "EXPENSE"],
    ["DLP", "Symantec DLP subscription ₹45000/month.", "billing@symantec.com", "EXPENSE"],
    ["CASB", "McAfee MVISION subscription ₹32000/month.", "billing@mcafee.com", "EXPENSE"],
    ["CASB", "Microsoft Defender for Cloud Apps subscription included.", "billing@microsoft.com", "EXPENSE"],
    ["Email security", "Mimecast subscription ₹25000/month.", "billing@mimecast.com", "EXPENSE"],
    ["Email security", "Barracuda subscription ₹18000/month.", "billing@barracuda.com", "EXPENSE"],
    ["Email security", "Proofpoint subscription ₹35000/month.", "billing@proofpoint.com", "EXPENSE"],
    ["Email security", "Abnormal Security subscription ₹28000/month.", "billing@abnormal.com", "EXPENSE"],
    ["Threat intel", "Recorded Future subscription ₹45000/month.", "billing@recordedfuture.com", "EXPENSE"],
    ["Threat intel", "ThreatConnect subscription ₹25000/month.", "billing@threatconnect.com", "EXPENSE"],
    ["Threat intel", "Flashpoint subscription ₹35000/month.", "billing@flashpoint.io", "EXPENSE"],
    ["Vulnerability mgmt", "Tenable subscription ₹32000/month.", "billing@tenable.com", "EXPENSE"],
    ["Vulnerability mgmt", "Rapid7 subscription ₹28000/month.", "billing@rapid7.com", "EXPENSE"],
    ["Vulnerability mgmt", "Qualys subscription ₹35000/month.", "billing@qualys.com", "EXPENSE"],
    ["Penetration testing", "Cobalt subscription ₹18000/month.", "billing@cobalt.io", "EXPENSE"],
    ["Penetration testing", "HackerOne subscription ₹25000/month.", "billing@hackerone.com", "EXPENSE"],
    ["Penetration testing", "Bugcrowd subscription ₹22000/month.", "billing@bugcrowd.com", "EXPENSE"],
]

NOT_EXPENSE_SAMPLES = [
    ["Weekly newsletter: AI trends", "This week in AI: New breakthroughs, research papers, and industry updates.", "newsletter@aiweekly.com", "NOT_EXPENSE"],
    ["Your order has shipped", "Your Amazon order #345-678901 has been shipped. Track your package.", "shipping@amazon.in", "NOT_EXPENSE"],
    ["Welcome to our platform", "Welcome! Complete your profile to get started with our service.", "welcome@platform.com", "NOT_EXPENSE"],
    ["Password reset request", "Someone requested a password reset for your account. Was this you?", "security@app.com", "NOT_EXPENSE"],
    ["New feature launch", "We've launched a new feature! Watch our video tutorial to learn more.", "product@company.com", "NOT_EXPENSE"],
    ["Survey invitation", "Help us improve! Take our 2-minute survey about your experience.", "survey@feedback.com", "NOT_EXPENSE"],
    ["Webinar reminder tomorrow", "Don't forget! Join our webinar tomorrow at 3 PM IST.", "events@webinar.com", "NOT_EXPENSE"],
    ["Your subscription is active", "Your free subscription is active. Upgrade to premium for more features.", "info@service.com", "NOT_EXPENSE"],
    ["New blog post", "New article: '10 Productivity Hacks' is now live. Read it now.", "blog@company.com", "NOT_EXPENSE"],
    ["Email verification needed", "Please verify your email address to continue using our service.", "verify@app.com", "NOT_EXPENSE"],
    ["Job alert: 3 new matches", "Based on your profile, we found 3 job openings that match your skills.", "jobs@careers.com", "NOT_EXPENSE"],
    ["System maintenance", "Scheduled maintenance on Sunday 2-4 AM. Services may be unavailable.", "admin@platform.com", "NOT_EXPENSE"],
    ["Weekly digest", "Top 5 stories this week: Technology, Business, and more.", "digest@news.com", "NOT_EXPENSE"],
    ["Profile viewed", "Your LinkedIn profile was viewed by 8 recruiters this week.", "notifications@linkedin.com", "NOT_EXPENSE"],
    ["New follower", "You have a new follower! Check out their profile.", "notification@social.com", "NOT_EXPENSE"],
    ["Weekly activity summary", "Here's your weekly activity summary on our platform.", "summary@service.com", "NOT_EXPENSE"],
    ["Town hall invitation", "Join us for the Q1 company town hall this Friday at 4 PM.", "events@company.com", "NOT_EXPENSE"],
    ["Free course available", "Enroll in our free course: 'Introduction to AI'. Limited spots!", "courses@learning.com", "NOT_EXPENSE"],
    ["Thank you for feedback", "Thank you for your feedback! We've incorporated your suggestions.", "support@service.com", "NOT_EXPENSE"],
    ["New podcast episode", "New episode: 'The Future of Work' is now available.", "podcast@studio.com", "NOT_EXPENSE"],
    ["Update preferences", "Manage your email preferences. Choose which updates you want.", "preferences@mailer.com", "NOT_EXPENSE"],
    ["Holiday greetings", "Wishing you and your family a happy holiday season!", "greetings@company.com", "NOT_EXPENSE"],
    ["Beta program invite", "Join our exclusive beta program and get early access to new features.", "beta@product.com", "NOT_EXPENSE"],
    ["Security alert", "We detected a new login to your account from a new device.", "security@platform.com", "NOT_EXPENSE"],
    ["Monthly report ready", "Your monthly report is ready to download.", "reports@analytics.com", "NOT_EXPENSE"],
    ["Guidelines updated", "We've updated our community guidelines. Please review.", "policy@platform.com", "NOT_EXPENSE"],
    ["New product announcement", "Introducing our latest product! Learn more about its features.", "launch@company.com", "NOT_EXPENSE"],
    ["Meeting scheduled", "Your meeting with the sales team is scheduled for Tuesday at 2 PM.", "calendar@company.com", "NOT_EXPENSE"],
    ["Account expiration", "Your account will expire in 30 days. Renew to continue.", "billing@service.com", "NOT_EXPENSE"],
    ["You were mentioned", "Someone mentioned you in a comment. Click to view.", "notification@platform.com", "NOT_EXPENSE"],
    ["Weekly goals update", "Here's your weekly goals progress. You're on track!", "goals@productivity.com", "NOT_EXPENSE"],
    ["Badge earned", "Congratulations! You've earned the 'Early Adopter' badge.", "achievements@platform.com", "NOT_EXPENSE"],
    ["Support ticket resolved", "Your support ticket #12345 has been resolved.", "support@company.com", "NOT_EXPENSE"],
    ["Team event invitation", "You're invited to our team building event next Friday.", "events@company.com", "NOT_EXPENSE"],
    ["Data export ready", "Your data export request is complete. Download before it expires.", "data@platform.com", "NOT_EXPENSE"],
    ["Dark mode available", "Dark mode is now available! Update your settings.", "product@company.com", "NOT_EXPENSE"],
    ["Quarterly newsletter", "Q1 Newsletter: Top highlights and updates from our team.", "newsletter@company.com", "NOT_EXPENSE"],
    ["Subscription expiring", "Your subscription expires in 7 days. Renew to continue.", "renewal@service.com", "NOT_EXPENSE"],
    ["Weekly challenge", "This week's challenge: Complete 5 tasks. Win rewards!", "challenges@platform.com", "NOT_EXPENSE"],
    ["API docs updated", "We've updated our API documentation with new endpoints.", "docs@developer.com", "NOT_EXPENSE"],
    ["You're trending", "Your post is trending! 500+ views in the last hour.", "notification@platform.com", "NOT_EXPENSE"],
    ["Learning path recommended", "Based on your interests, we recommend the 'Data Science' path.", "recommendations@learning.com", "NOT_EXPENSE"],
    ["Free trial extension", "We've extended your free trial by 7 days. Enjoy!", "promo@service.com", "NOT_EXPENSE"],
    ["Forum answer", "Your question on our forum has been answered by an expert.", "forum@community.com", "NOT_EXPENSE"],
    ["Connection request", "You have a new connection request on our professional network.", "network@platform.com", "NOT_EXPENSE"],
    ["Weekly leaderboard", "Check out this week's top performers. Are you on the list?", "leaderboard@platform.com", "NOT_EXPENSE"],
    ["Price drop alert", "An item in your wishlist is now 20% off. Limited time!", "deals@shopping.com", "NOT_EXPENSE"],
    ["Conference registration", "Register for our annual conference. Early bird discounts available.", "events@conference.com", "NOT_EXPENSE"],
    ["Session saved", "Your work session was automatically saved. No data lost.", "system@productivity.com", "NOT_EXPENSE"],
    ["New templates", "We've added 5 new templates to help you work faster.", "templates@productivity.com", "NOT_EXPENSE"],
    ["Achievement unlocked", "You've unlocked a new achievement: '100 Day Streak'!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Monthly summary", "Your monthly activity summary is ready. View your progress.", "summary@platform.com", "NOT_EXPENSE"],
    ["Featured content", "Your work has been featured in our 'Spotlight' section.", "editorial@platform.com", "NOT_EXPENSE"],
    ["Collaboration tools", "Explore our new collaboration features for teams.", "product@company.com", "NOT_EXPENSE"],
    ["Feedback appreciated", "Thanks to your feedback, we've improved our service.", "product@company.com", "NOT_EXPENSE"],
    ["Webinar series", "Join our 3-part webinar series on industry trends.", "webinars@learning.com", "NOT_EXPENSE"],
    ["Storage full warning", "Your cloud storage is 90% full. Upgrade for more space.", "storage@cloud.com", "NOT_EXPENSE"],
    ["App update", "Version 2.5 is now available. Download for new features.", "app@company.com", "NOT_EXPENSE"],
    ["Winning streak", "You've won 5 challenges in a row! Keep it up.", "challenges@platform.com", "NOT_EXPENSE"],
    ["User group meetup", "Join our local user group meetup this Saturday.", "meetups@community.com", "NOT_EXPENSE"],
    ["Content shared", "Your insights were shared in our weekly newsletter.", "newsletter@platform.com", "NOT_EXPENSE"],
    ["New integrations", "We've added integration with popular apps. Connect now.", "integrations@platform.com", "NOT_EXPENSE"],
    ["Open source contribution", "Your contribution to our open source project has been appreciated.", "opensource@company.com", "NOT_EXPENSE"],
    ["Goals completed", "Congratulations! You've completed all your weekly goals.", "goals@productivity.com", "NOT_EXPENSE"],
    ["Learning resources", "We've added 20 new tutorials to our learning center.", "learning@education.com", "NOT_EXPENSE"],
    ["Profile complete", "Your profile is now 100% complete. You're all set!", "onboarding@platform.com", "NOT_EXPENSE"],
    ["Security tips", "Read our latest article on security best practices.", "security@platform.com", "NOT_EXPENSE"],
    ["Milestone reached", "Congratulations! You've completed 100 tasks on our platform.", "milestones@platform.com", "NOT_EXPENSE"],
    ["Feature request", "Thank you for your feature request! We've added it to our roadmap.", "feedback@company.com", "NOT_EXPENSE"],
    ["Community digest", "Top community posts this week. Join the conversation!", "digest@community.com", "NOT_EXPENSE"],
    ["Subscription active", "Your annual subscription is active until December 2026.", "subscription@service.com", "NOT_EXPENSE"],
    ["Research paper", "Our team published a new research paper on AI ethics.", "research@company.com", "NOT_EXPENSE"],
    ["Beta testing invite", "Be among the first to test our new features. Join the beta.", "beta@product.com", "NOT_EXPENSE"],
    ["Workspace created", "Your new workspace has been created. Start collaborating.", "workspace@platform.com", "NOT_EXPENSE"],
    ["Productivity tips", "Here are 5 tips to boost your productivity this week.", "tips@productivity.com", "NOT_EXPENSE"],
    ["New podcast", "Episode 42: 'Building Great Teams' is now available.", "podcast@studio.com", "NOT_EXPENSE"],
    ["Forum featured", "Your question on our Q&A forum has been featured.", "forum@community.com", "NOT_EXPENSE"],
    ["First contribution", "Congratulations on your first contribution to our community!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Real-time features", "We've launched real-time collaboration. Work together!", "product@company.com", "NOT_EXPENSE"],
    ["Progress report", "View your monthly progress report with detailed analytics.", "reports@platform.com", "NOT_EXPENSE"],
    ["Challenge winner", "Congratulations! You're this week's challenge winner.", "challenges@platform.com", "NOT_EXPENSE"],
    ["Tool integrations", "We've added integration with Slack, Teams, and Zoom.", "integrations@platform.com", "NOT_EXPENSE"],
    ["Feedback impact", "Your feedback led to 3 new features in our latest update.", "product@company.com", "NOT_EXPENSE"],
    ["Virtual meetup", "Join our virtual meetup this Thursday. Topic: Industry Trends.", "events@community.com", "NOT_EXPENSE"],
    ["Content viral", "Your content has been shared 100+ times this week.", "viral@platform.com", "NOT_EXPENSE"],
    ["Advanced learning", "We've launched an advanced learning path for experienced users.", "learning@education.com", "NOT_EXPENSE"],
    ["Streak continues", "You're on a 30-day streak! Keep the momentum going.", "streak@platform.com", "NOT_EXPENSE"],
    ["Community guidelines", "We've updated our community guidelines. Please review.", "policy@community.com", "NOT_EXPENSE"],
    ["Subscription renewal", "Your subscription will automatically renew on April 1.", "billing@service.com", "NOT_EXPENSE"],
    ["Community helper", "You've earned the 'Community Helper' badge. Wear it!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Dark mode launch", "We've launched dark mode across all our apps. Update now!", "launch@company.com", "NOT_EXPENSE"],
    ["Workspace settings", "Review and update your workspace settings for collaboration.", "settings@platform.com", "NOT_EXPENSE"],
    ["Top creators", "Meet our top creators this week. Get inspired!", "digest@community.com", "NOT_EXPENSE"],
    ["API endpoints", "We've added 10 new API endpoints to our developer portal.", "docs@developer.com", "NOT_EXPENSE"],
    ["Account security", "Review your account security settings. 2FA recommended.", "security@platform.com", "NOT_EXPENSE"],
    ["Recommended posts", "Our algorithm recommends checking out these trending posts.", "recommendations@platform.com", "NOT_EXPENSE"],
    ["Templates library", "Browse our expanded templates library with 50+ designs.", "templates@productivity.com", "NOT_EXPENSE"],
    ["Weekly achievements", "Here are your achievements for this week. Great job!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Cloud partnerships", "We've partnered with leading cloud providers. Integrate now!", "partnerships@company.com", "NOT_EXPENSE"],
    ["Content performance", "Your content has performed 20% better this week.", "analytics@platform.com", "NOT_EXPENSE"],
    ["Community event", "Join our monthly community showcase. Present your work!", "events@community.com", "NOT_EXPENSE"],
    ["Subscription benefits", "Explore all benefits included in your subscription.", "benefits@service.com", "NOT_EXPENSE"],
    ["Creative challenge", "This week's creative challenge: Design a logo. Submit now!", "challenges@platform.com", "NOT_EXPENSE"],
    ["Voice notes", "You can now add voice notes to your projects. Try it out!", "product@company.com", "NOT_EXPENSE"],
    ["Network growing", "You've gained 25 new followers this week. Expand your reach!", "network@platform.com", "NOT_EXPENSE"],
    ["Research publication", "Our research team published a paper on machine learning.", "research@company.com", "NOT_EXPENSE"],
    ["Privacy settings", "Review and update your privacy settings. Your data matters.", "privacy@platform.com", "NOT_EXPENSE"],
    ["Innovation digest", "This week's focus: Innovation in tech. Read the latest.", "newsletter@techweekly.com", "NOT_EXPENSE"],
    ["Team building", "Join our virtual team building session on Friday at 5 PM.", "events@company.com", "NOT_EXPENSE"],
    ["New badge available", "New badge unlocked: 'Problem Solver'. Check your achievements.", "achievements@platform.com", "NOT_EXPENSE"],
    ["Feature spotlight", "This month's feature spotlight: Advanced search capabilities.", "product@company.com", "NOT_EXPENSE"],
    ["Community spotlight", "Meet our top contributors this month. Thank you for your impact!", "digest@community.com", "NOT_EXPENSE"],
    ["Tips and tricks", "5 tips to get the most out of our platform this week.", "tips@productivity.com", "NOT_EXPENSE"],
    ["User stories", "Read how our users are solving problems with our platform.", "stories@company.com", "NOT_EXPENSE"],
    ["Event recap", "Here's a recap of last week's virtual meetup. Watch now!", "events@community.com", "NOT_EXPENSE"],
    ["Integration guides", "New integration guides available for Salesforce and HubSpot.", "docs@developer.com", "NOT_EXPENSE"],
    ["Weekly digest: Product", "Product updates, new features, and what's coming next.", "digest@product.com", "NOT_EXPENSE"],
    ["Beta access granted", "You've been granted early access to our beta program. Start testing!", "beta@product.com", "NOT_EXPENSE"],
    ["Community guidelines", "Please review our updated community guidelines before posting.", "policy@community.com", "NOT_EXPENSE"],
    ["Feature roadmap", "See what's coming next on our product roadmap.", "roadmap@company.com", "NOT_EXPENSE"],
    ["User feedback", "Your recent feedback has helped us improve our platform. Thank you!", "feedback@company.com", "NOT_EXPENSE"],
    ["Learning path updated", "We've updated our 'Data Science' learning path with new content.", "learning@education.com", "NOT_EXPENSE"],
    ["Weekly challenge: Creative", "This week's creative challenge: Share your workspace setup.", "challenges@platform.com", "NOT_EXPENSE"],
    ["New integration: Zapier", "Connect our platform with Zapier to automate your workflows.", "integrations@platform.com", "NOT_EXPENSE"],
    ["Achievement leaderboard", "Check the monthly achievement leaderboard. Are you on top?", "leaderboard@platform.com", "NOT_EXPENSE"],
    ["Security update", "We've enhanced our security measures. Review your account settings.", "security@platform.com", "NOT_EXPENSE"],
    ["Community poll", "Vote on our latest community poll: What feature do you want next?", "poll@community.com", "NOT_EXPENSE"],
    ["Weekly recap", "Your weekly activity recap is ready. See what you accomplished!", "summary@platform.com", "NOT_EXPENSE"],
    ["New templates: Business", "We've added 10 new business templates to our library.", "templates@productivity.com", "NOT_EXPENSE"],
    ["Feature tutorial", "New tutorial: How to use our advanced search feature.", "tutorials@company.com", "NOT_EXPENSE"],
    ["Community shoutout", "Special shoutout to our top 10 contributors this month!", "digest@community.com", "NOT_EXPENSE"],
    ["Product update: v2.6", "Version 2.6 is now live! See what's new and improved.", "updates@company.com", "NOT_EXPENSE"],
    ["Weekly goals tracker", "Your weekly goals are on track. Keep up the great work!", "goals@productivity.com", "NOT_EXPENSE"],
    ["Learning milestone", "Congratulations on completing 10 courses this month!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Integration success", "You've successfully integrated with 5 new tools!", "integrations@platform.com", "NOT_EXPENSE"],
    ["Content recommendation", "Based on your interests, we recommend these articles.", "recommendations@content.com", "NOT_EXPENSE"],
    ["Weekly challenge winner", "Congratulations to last week's challenge winner: @johndoe!", "challenges@platform.com", "NOT_EXPENSE"],
    ["Feature request implemented", "The feature you requested is now live! Thank you for your input.", "feedback@company.com", "NOT_EXPENSE"],
    ["Community guidelines reminder", "Friendly reminder: Please follow our community guidelines.", "policy@community.com", "NOT_EXPENSE"],
    ["Weekly insights", "Here are your weekly insights and performance metrics.", "analytics@platform.com", "NOT_EXPENSE"],
    ["New badge: Innovator", "New badge available: Innovator. Awarded for creative contributions.", "achievements@platform.com", "NOT_EXPENSE"],
    ["Product roadmap update", "We've updated our product roadmap with new features for Q2.", "roadmap@company.com", "NOT_EXPENSE"],
    ["Learning path: Advanced", "New advanced learning path: Machine Learning for Developers.", "learning@education.com", "NOT_EXPENSE"],
    ["Community event: Workshop", "Join our virtual workshop on 'Best Practices' this Thursday.", "events@community.com", "NOT_EXPENSE"],
    ["Integration guide", "New guide: How to integrate with our REST API.", "docs@developer.com", "NOT_EXPENSE"],
    ["Weekly digest: Updates", "This week's updates: Bug fixes, performance improvements, more.", "digest@updates.com", "NOT_EXPENSE"],
    ["Feature beta testing", "Help us test our new feature! Sign up for beta access.", "beta@product.com", "NOT_EXPENSE"],
    ["User spotlight", "This week's user spotlight: @janedoe and her amazing project.", "digest@community.com", "NOT_EXPENSE"],
    ["Weekly challenge: Design", "This week's design challenge: Create a stunning banner.", "challenges@platform.com", "NOT_EXPENSE"],
    ["New integration: Notion", "We've added integration with Notion. Connect your workspace!", "integrations@platform.com", "NOT_EXPENSE"],
    ["Achievement unlocked: Mentor", "You've unlocked the 'Mentor' achievement. Help 10 more users!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Security best practices", "New article: 5 security best practices for your account.", "security@platform.com", "NOT_EXPENSE"],
    ["Community poll results", "Results from our latest poll: What's next for our platform?", "poll@community.com", "NOT_EXPENSE"],
    ["Weekly recap: Highlights", "Your weekly recap highlights: 5 tasks completed, 2 badges earned.", "summary@platform.com", "NOT_EXPENSE"],
    ["New templates: Design", "We've added 15 new design templates to our library.", "templates@productivity.com", "NOT_EXPENSE"],
    ["Feature tutorial video", "New video tutorial: Mastering our advanced features.", "tutorials@company.com", "NOT_EXPENSE"],
    ["Community milestones", "Our community has reached 100,000 members! Thank you all!", "digest@community.com", "NOT_EXPENSE"],
    ["Product update: v2.7", "Version 2.7 is live! See what's new and improved.", "updates@company.com", "NOT_EXPENSE"],
    ["Weekly goals celebration", "You've exceeded your weekly goals! Keep it up!", "goals@productivity.com", "NOT_EXPENSE"],
    ["Learning milestone: 50 courses", "Congratulations on completing 50 courses! You're a learning champion!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Integration milestone", "You've integrated with 10+ tools. Impressive!", "integrations@platform.com", "NOT_EXPENSE"],
    ["Content recommendation", "Trending content this week: AI, Productivity, and Design.", "recommendations@content.com", "NOT_EXPENSE"],
    ["Weekly challenge leaderboard", "Top 10 on this week's challenge leaderboard. Are you there?", "challenges@platform.com", "NOT_EXPENSE"],
    ["Feature request status", "Your feature request is now 'In Progress'. We'll keep you updated!", "feedback@company.com", "NOT_EXPENSE"],
    ["Community guidelines FAQ", "New FAQ section added to our community guidelines.", "policy@community.com", "NOT_EXPENSE"],
    ["Weekly insights: Growth", "Your weekly insights: 15% increase in engagement!", "analytics@platform.com", "NOT_EXPENSE"],
    ["New badge: Leader", "New badge available: Leader. Awarded for community leadership.", "achievements@platform.com", "NOT_EXPENSE"],
    ["Product roadmap: Q2", "Q2 product roadmap is now available. See what's coming!", "roadmap@company.com", "NOT_EXPENSE"],
    ["Learning path: Expert", "New expert-level learning path: Advanced AI Concepts.", "learning@education.com", "NOT_EXPENSE"],
    ["Community event: Hackathon", "Join our virtual hackathon this weekend. Theme: AI for Good.", "events@community.com", "NOT_EXPENSE"],
    ["Integration guide: Webhooks", "New guide: Setting up webhooks for real-time updates.", "docs@developer.com", "NOT_EXPENSE"],
    ["Weekly digest: Announcements", "This week's announcements: New features, events, and more.", "digest@announcements.com", "NOT_EXPENSE"],
    ["Feature beta: AI assistant", "Try our new AI assistant beta. Give us your feedback!", "beta@product.com", "NOT_EXPENSE"],
    ["User spotlight: Innovators", "This week's spotlight: Our most innovative users and their projects.", "digest@community.com", "NOT_EXPENSE"],
    ["Weekly challenge: AI", "This week's challenge: Create something with our new AI features.", "challenges@platform.com", "NOT_EXPENSE"],
    ["New integration: Trello", "We've added integration with Trello. Manage your tasks!", "integrations@platform.com", "NOT_EXPENSE"],
    ["Achievement unlocked: Visionary", "You've unlocked the 'Visionary' achievement. Predict the future!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Security audit complete", "Our latest security audit is complete. Your data is safe.", "security@platform.com", "NOT_EXPENSE"],
    ["Community poll: Features", "New poll: Which feature should we build next? Vote now!", "poll@community.com", "NOT_EXPENSE"],
    ["Weekly recap: Achievements", "Your weekly recap: 3 new badges, 2 integrations, 100% goals.", "summary@platform.com", "NOT_EXPENSE"],
    ["New templates: Marketing", "We've added 20 new marketing templates to our library.", "templates@productivity.com", "NOT_EXPENSE"],
    ["Feature tutorial: Automation", "New tutorial: Automating your workflows with our tools.", "tutorials@company.com", "NOT_EXPENSE"],
    ["Community celebration", "Celebrating our community's 1-year anniversary! Here's to many more!", "digest@community.com", "NOT_EXPENSE"],
    ["Product update: v2.8", "Version 2.8 is now live! Major performance improvements.", "updates@company.com", "NOT_EXPENSE"],
    ["Weekly goals: Perfect", "You've achieved a perfect 100% on your weekly goals!", "goals@productivity.com", "NOT_EXPENSE"],
    ["Learning milestone: 100 courses", "Congratulations on completing 100 courses! Learning legend!", "achievements@platform.com", "NOT_EXPENSE"],
    ["Integration milestone: 20 tools", "You've integrated with 20+ tools. Integration master!", "integrations@platform.com", "NOT_EXPENSE"],
    ["Content recommendation: Viral", "Trending viral content: Top 10 posts this week.", "recommendations@content.com", "NOT_EXPENSE"],
    ["Weekly challenge: Collaboration", "This week's challenge: Collaborate with another user.", "challenges@platform.com", "NOT_EXPENSE"],
    ["Feature request: Delivered", "Great news! Your feature request is now live. Enjoy!", "feedback@company.com", "NOT_EXPENSE"],
    ["Community guidelines: Update", "We've updated our community guidelines with new policies.", "policy@community.com", "NOT_EXPENSE"],
    ["Weekly insights: Engagement", "Your weekly insights: 25% increase in community engagement.", "analytics@platform.com", "NOT_EXPENSE"],
    ["New badge: Champion", "New badge available: Champion. Awarded to top performers.", "achievements@platform.com", "NOT_EXPENSE"],
    ["Product roadmap: Q3", "Q3 product roadmap is now available. Exciting things coming!", "roadmap@company.com", "NOT_EXPENSE"],
    ["Learning path: Specialist", "New specialist learning path: Cloud Architecture.", "learning@education.com", "NOT_EXPENSE"],
    ["Community event: Conference", "Join our virtual conference next month. Keynote speakers announced!", "events@community.com", "NOT_EXPENSE"],
    ["Integration guide: Mobile SDK", "New guide: Using our Mobile SDK for iOS and Android.", "docs@developer.com", "NOT_EXPENSE"],
    ["Weekly digest: Success stories", "This week's success stories: How users are achieving their goals.", "digest@success.com", "NOT_EXPENSE"],
    ["Feature beta: Dark mode", "Dark mode beta is now available for testing. Give it a try!", "beta@product.com", "NOT_EXPENSE"],
    ["User spotlight: Rising stars", "This week's spotlight: Our rising stars in the community.", "digest@community.com", "NOT_EXPENSE"],
]


def create_expanded_dataset(input_csv: Path, output_csv: Path, expense_samples: list, not_expense_samples: list) -> dict:
    """Create expanded dataset with 1000 rows."""
    existing_rows = []
    
    with open(input_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        for row in reader:
            existing_rows.append(row)
    
    for sample in expense_samples:
        row_dict = {
            "subject": sample[0],
            "body": sample[1],
            "sender": sample[2],
            "label": sample[3]
        }
        existing_rows.append(row_dict)
    
    for sample in not_expense_samples:
        row_dict = {
            "subject": sample[0],
            "body": sample[1],
            "sender": sample[2],
            "label": sample[3]
        }
        existing_rows.append(row_dict)
    
    with open(output_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(existing_rows)
    
    label_counts = {}
    for row in existing_rows:
        label = row["label"]
        label_counts[label] = label_counts.get(label, 0) + 1
    
    return {
        "original_count": 259,
        "expense_added": len(expense_samples),
        "not_expense_added": len(not_expense_samples),
        "final_count": len(existing_rows),
        "label_distribution": label_counts
    }


def print_expansion_report(stats: dict) -> None:
    """Print expansion report."""
    print("\n" + "=" * 60)
    print("TRAINING DATA EXPANSION TO 1000 ROWS")
    print("=" * 60)
    
    print(f"\n📊 Summary:")
    print(f"   Original count: {stats['original_count']}")
    print(f"   EXPENSE samples added: {stats['expense_added']}")
    print(f"   NOT_EXPENSE samples added: {stats['not_expense_added']}")
    print(f"   Final count: {stats['final_count']}")
    
    print(f"\n📈 Label Distribution:")
    for label, count in stats["label_distribution"].items():
        percentage = (count / stats["final_count"]) * 100
        print(f"   {label}: {count} ({percentage:.1f}%)")
    
    print("\n" + "=" * 60)


if __name__ == "__main__":
    stats = create_expanded_dataset(TRAINING_CSV, EXPANDED_CSV, EXPENSE_SAMPLES, NOT_EXPENSE_SAMPLES)
    print_expansion_report(stats)
